// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
const { defineConfig, env } = require('prisma/config');
require('dotenv/config');

module.exports = defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Standard JS way to get your DB URL
    url: env('DATABASE_URL'),
  },
});
// Note: Ensure that your .env file is correctly set up with DATABASE_URL variable.

